name: prepare publish check

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  build-develop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: install packages
        run: yarn
      - name: check format
        run: yarn check-format
      - name: check lint
        run: yarn check-types
      - name: check types
        run: yarn check-types
      - name: check build next
        run: yarn build